### PR TITLE
Brightness fix

### PR DESCRIPTION
**Pull request by lubosz**
These 3 patches allow the user to lower the brightness level as low as 1 in `/sys/class/backlight/backlight/brightness`.
The user facing range will be 0-100%, while the actual written range will be 1-100%.

In addition I map the ES value quadratically to the hardware value: 
es-brightness

This makes the lower range values occupy more space in the range, resulting in a more linear transition on the screen.

I actually could measure the screen brightness using a colorimeter to come up with a function based on calibration, but this is better than before.

### CODE REVIEW

**Comment by shantigilbert** [comment]
Thanks for the PR! but can you ifdef all the changes related to EmuELEC?

It makes it easier to track 

Use something like this

```
#ifdef _ENABLEEMUELEC
// your code 
#else
// original code
#endif
```

**Comment by lubosz** [comment]
I don't understand this `#ifdef`. If you wanted to build batocera's emulationstation, which then not use their branch directly without your patch set?
This will blow up your code quite a bit and make it very hard to maintain.
I will upstream my changes to batocera directly in this case, so they won't need to be ifdeffed in EmuELEC.

**Comment by shantigilbert** [comment]
Up to you :)

**Comment by shantigilbert** [comment]
Gonna go ahead and close this, feel free to reopen if needed.

**Pull request closed without merging**
